sequenceDiagram
    actor A as Клиент
    participant B as Сервер
    A ->>+ B: Дай последнюю версию проекта!
    B -->>- A: Перекидывает архив с проектом
    A ->> A: Правит файл foo.py!
    A ->>+ B: Я заливаю изменения!
    B -->>- A: Принимает изменения
    A ->>+ B: Дай изменения проекта!
    B -->>- A: Отправляет изменения от коллег
