sequenceDiagram
    actor A as Клиент
    participant B as Сервер
    A ->>+ B: Дай последнюю версию проекта!
    B -->>- A: Перекидывает архив с проектом
    A ->>+ B: Я начинаю править файл foo.py!
    B -->> A: Помечает файл заблокированным и отдаёт последнюю версию
    A ->> B: Я заливаю изменения!
    B -->>- A: Сохраняет у себя файл и снимает блокировку
